# Generated by Django 5.2 on 2025-08-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablascatalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'Estados', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='incidencias',
            options={'verbose_name': 'Tabla de Incidentes', 'verbose_name_plural': 'Tabla de Incidentes'},
        ),
        migrations.AlterModelOptions(
            name='nivel1',
            options={'verbose_name': 'Nivel1', 'verbose_name_plural': 'Nivel1'},
        ),
        migrations.AlterModelOptions(
            name='nivel2',
            options={'verbose_name': 'Nivel2', 'verbose_name_plural': 'Nivel2'},
        ),
        migrations.AlterModelOptions(
            name='nivel3',
            options={'verbose_name': 'Nivel3', 'verbose_name_plural': 'Nivel3'},
        ),
       
    ]
