# Generated by Django 5.2 on 2025-08-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablascatalogos', '0002_alter_estados_options_alter_incidencias_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estados',
            name='estado_incidencia',
        ),
    ]
