"""
Django settings for Aplicacion project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q3scphbh#iar59&0q$9wkzxc#*57uumzh95_(!9&4--z_)$2&0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tablascatalogos',
    'incidencias',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Aplicacion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Aplicacion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'apphotelsw',  # Reemplaza con el nombre de tu base de datos
        'USER': 'postgres',                    # Usuario por defecto de PostgreSQL
        'PASSWORD': '123456',           # Reemplaza con la contraseña de postgres
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-es'


#TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

#USE_TZ = True
USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'

# Carpeta donde collectstatic juntará todo
STATIC_ROOT = BASE_DIR / "staticfiles"

# (Opcional) Carpeta donde tú guardas tus estáticos mientras desarrollas
STATICFILES_DIRS = [
    BASE_DIR / "static",
]



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    # Título del sitio en el admin
    "site_title": "Aplicación",
    "site_header": "Aplicación",
    "site_brand": "Aplicación SH",
    
    # Texto de copyright en el pie de página
    "copyright": "Aplicación SH - Todos los derechos reservados 2025",
    
    # Ocultar la versión de Jazzmin
    "show_ui_builder": False,  # Quita el botón de personalización
    "hide_jazzmin_version": True, 

    "welcome_sign": "Bienvenido",
    

    
    # Logotipo para la página de login y el admin
    "site_logo": "img/logo.png",
    #"site_logo_classes": "img-circle",

    # Configuración existente
    "theme": "flatly",
    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_links": {
        "catalogos": [
            {
                "name": "Dashboard",
                "url": "dashboard",
                "icon": "fas fa-tachometer-alt",
            },
            {
                "name": "Nivel",
                "url": "nivel",
                "icon": "fas fa-layer-group",
            },
            {
                "name": "Nivel1",
                "url": "nivel1",
                "icon": "fas fa-layer-group",
            },
            {
                "name": "Nivel2",
                "url": "nivel2",
                "icon": "fas fa-layer-group",
            },
            {
                "name": "Nivel3",
                "url": "nivel3",
                "icon": "fas fa-layer-group",
            },
            {
                "name": "Incidencias",
                "url": "incidencias",
                "icon": "fas fa-exclamation-triangle",
            },
            {
                "name": "Estados",
                "url": "estados",
                "icon": "fas fa-flag",
            },
        ],
        "moduloautentificacion": [
            {
                "name": "Incidencia",
                "url": "admin:moduloautentificacion_incidencia_changelist",
                "icon": "fas fa-bug",
            },
        ],
    },
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "custom_css": None,
    "custom_js": None,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-light",  # Navbar claro para combinar con el tema
    "accent": "accent-primary",
    "navbar": "navbar-light",  # Navbar blanco
    "no_navbar_border": False,
    "sidebar": "sidebar-light-red",  # Sidebar blanco
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}

