# Generated by Django 5.2 on 2025-08-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummy',
            options={'managed': False, 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboard'},
        ),
    ]
