# Generated by Django 5.2 on 2025-08-13 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablascatalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('observacion_destinatario', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_abierto', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablascatalogos.estados')),
                ('id_nivel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablascatalogos.nivel1')),
                ('id_nivel2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablascatalogos.nivel2')),
                ('id_nivel3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablascatalogos.nivel3')),
                ('incidencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablascatalogos.incidencias')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
