# Generated by Django 5.2 on 2025-08-17 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
        ('tablascatalogos', '0002_alter_estados_options_alter_incidencias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_abierto',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='incidencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablascatalogos.incidencias'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='observacion_destinatario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
